name: Daily Scraper

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
jobs:
  notebooks:
    name: Run the notebook
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10.9'

      - name: Setup Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: anaconda-client-env
          environment-file: environment.yml
          auto-activate-base: false

      - name: Run Python Notebooks
        working-directory: ./notebooks
        run: |
          chmod u+r+x ./runallnotebooks.sh
          ./runallnotebooks.sh

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./notebooks/exports